apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service_loopback.type }}
  ports:
    - port: {{ .Values.service_loopback.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service_mongodb.type }}
  ports:
    - port: {{ .Values.service_mongodb.port }}
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
